domain: "localhost"
museum_port: 8080
web_ports:
  photos: 3000
  accounts: 3001
  albums: 3002
  auth: 3003
  cast: 3004

db:
  password: "db_password"

jwt_secret: "eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJlXzMyX2NoYXJz"
enc_key: "eW91cl9lbmNyeXB0aW9uX2tleV9oZXJlXzMyX2NoYXJz"
hash_key: "eW91cl9oYXNoX2tleV9oZXJlXzMyX2NoYXJhY3RlcnM="

s3:
  key: "minioadmin"
  secret: "minioadmin123"